### ISSUE TITLE
Dimitrij should remove its own "like" after the first player has joined

### ISSUE THREAD

**Issue by wolfgangj** [mschneider85/dimitrij#1]
The displayed number is confusing because it's always one more than players that have joined the match. (If the last player leaves the match, the bot obviously needs to re-add itself so that players can still join.)

**Comment by mpw1337** [comment]
Game Breaking Bug!

**Comment by mschneider85** [comment]
Numbers should be correct, since the originator doesn't join a match. Tooltips of reactions **don't** reflect the correct match composition, though. Feel free to give some hints to solve this.
I'm leaving this open until the next release.
